### ISSUE TITLE
Opening/Closing Credits

### ISSUE THREAD

**Issue by infinityredux** [Pandarr/HyperRPGGameJam2017#5]

**Comment by infinityredux** [comment]
**Opening credits**
* TODO: Need to check with story team what they want from opening credits for narrative
* TODO: Also need to check that we don't duplicate something that's on the main menu (unless we explictly want to do that)
* Otherwise, something like "Team Thumper presents"

**Closing credits**
* Visually, I like the idea of both text fading in and out and scrolling
  * Initially something fading in and out, maybe this was a Team Thumper project type of thing
  * Then scrolling full credits
  * Then maybe thanks title staying on screen with the people being thanked fading in and out, lingering on the line thanking the player for a longer beat
  * Then fade to black
* Ideally should be timed to the music we're using
  * Don't Cry is 2:27, but we might use something else

**Aesthetics**
* White text on black is traditional credits
* Titles / roles need to be visually distinct (bold?)
* But there was also the idea of watching the sun set, so that would need a different colour palette

**Systems needed**
* Fade in and out
* Scrolling text
* Direct control of the timings for each (so it can be fitted to the music)
* Being able to alter fonts, styles, etc. (i.e. not hard coded) might be useful too

**Comment by infinityredux** [comment]
**Progress update**
- Core of the credits has been implemented mostly (see below). 
- Opening credits are very simple, but we can add more if needed for narrative viewpoint quite easily. 
- Waiting on the final credits document to be finalised to finish the names on the list. 

**Still to be implemented**
- No music has been implemented yet, in part because I didn't know if a decision has been made about what we would be playing over the end credits.
- Code outline is in place to allow user to exit the final credits by pressing escape, but actually needs to work / change scene / etc.
- General integrations with everything else.

**Known Problems**
Scrolling can't detect the size of the canvas at all for some reason (see the `StartScroll` function starting on line 75 in `CreditsTools.cs`). So it doesn't know where to position the text or when the text is off the screen. This may also have an impact on the initial positioning of the text for the credits (being too low or too high depending on the screen / canvas size).

**Other possible refinements**
- Font choice - the default Arial doesn't look that pretty (at least for me) at larger font sizes.
- Aesthetics - white on black is fairly traditional for credits, but no idea how it fits with the themes for the rest of the project, so may want to consider other colour schemes.
- Scrolling smoothness - adding a small movement increment and slightly longer delay between movement may produce smoother scrolling.
- The text fields accept rich text - does that open the possibility of specifying different font sizes, colours or using tags like &lt;h1&gt; to make the title parts more distinct?

**Comment by infinityredux** [comment]
- [x] Fix scrolling bug
- [x] Improve scrolling smoothness
- [ ] Alternative font
- [x] Explore rich text input options
- [ ] Aesthetic changes (if needed)

**Comment by kedomir** [comment]
- [ ] Add music?

**Comment by infinityredux** [comment]
Has been handed off for integration.
