### ISSUE TITLE
Menu Navigation and Options Menu

### ISSUE THREAD

**Issue by annamberg** [Pandarr/HyperRPGGameJam2017#6]
- [x] Make main menu
- [x] Make options menu
- [x] Navigate between options and main menu
- [x] Exit/quit game

**Start game:**
- [x] hide main menu
- [x] pan down

**Options:** 
- [x] mute music
- [x] change music level
- [x] Bring up options be pressing esc
- [x] Hide options by pressing esc?

**Comment by Counter-Weight** [comment]
When the play screen is too small, the options screen gets cut off half way down. Nothing too significant, I doubt anyone will be playing with a screen that small. It would be nice though to detect and/or somehow center it by screen size.

**Comment by annamberg** [comment]
The graphics/UI is not done, it's just placeholder things until we decide that colors/fonts/etc to use.

**Comment by Counter-Weight** [comment]
Ok great I'm partway to the camera panning down

**Comment by Counter-Weight** [comment]
Close this now?
